### 1. Import Numpy package under the name `np`

In [1]:
import numpy as np

### 2. Print the numpy version and the configuration

In [2]:
print(np.__version__)
np.show_config()

1.20.3
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/veyseng/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/veyseng/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/veyseng/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/veyseng/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/veyseng/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/veyseng/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/veyseng/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/veyseng/opt/anaconda3/include']


### 3. Create a null vector of size 10

In [3]:
num = np.zeros(10)
print(num)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. How to find the memory size of any array

In [4]:
num = np.zeros((10, 20))
print(f" %d bytes " % (num.size * num.itemsize))

 1600 bytes 


### 5. How to get the documentation of the numpy add function from the command line?

In [11]:
%psearch np.add*
np.lookfor('add')

Search results for 'add'
------------------------
numpy.add
    Add arguments element-wise.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.add_newdoc
    Add documentation to an existing object, typically one defined in C
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.ma.add
    Add arguments element-wise.
numpy.add_docstring
    Add a docstring to a built-in obj if possible.
numpy.quantile
    Compute the q-th quantile of the data along the specified axis.
numpy.deprecate
    Issues a DeprecationWarning, adds warning to `old_name`'s
numpy._add_newdoc_ufunc
    Replace the docstring for a ufunc with new_docstring.
numpy.binary_repr
    Return the binary representation of the input number as a string.
numpy.ma.ids
    ids(self)
numpy.fft.test
    Pytest test runner.
numpy.Str0.ljust
    Return a left-justified string of length width.
numpy.Str0.rjust
    Return a right-justified string of length width.
numpy.

In [13]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

### 6. Create a null vector of size 10 but the fifth value which is 1

In [14]:
nullity = np.zeros(10)
nullity[4] = 1
print(nullity)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Create a vector with values ranging from 10 to 49

In [16]:
num = np.arange(10, 50)
print(num)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 8. Reverse a vector (first element becomes last)

In [17]:
num = np.arange(50)
num = num[::-1]
print(num)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
num = np.arange(9).reshape(3, 3)
print(num)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 10. Find indices of non-zero elements from [1, 2, 0, 0, 4, 0]

In [20]:
num_nonzero = np.nonzero([1, 2, 0, 0 , 4, 0])
print(num_nonzero)

(array([0, 1, 4]),)


### 11. Create a 3x3 identity matrix

In [21]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 12. Create a 3x3x3 array with random values

In [23]:
num = np.random.random((3, 3, 3))
print(num)

[[[0.22599553 0.30415374 0.71499388]
  [0.72409148 0.01867644 0.2858131 ]
  [0.58048634 0.93078663 0.3389969 ]]

 [[0.12008312 0.51627271 0.69920706]
  [0.29864068 0.86160962 0.9058072 ]
  [0.76858325 0.26123164 0.9384556 ]]

 [[0.93864246 0.74504455 0.91073504]
  [0.23722471 0.49496735 0.80987834]
  [0.95456578 0.63748325 0.91084975]]]


###  13. Create a 10x10 array with random values and find the minimum and maximum values

In [24]:
random = np.random.random((10, 10))
randomMax, randomMin = random.max(), random.min()
print(f"Max: %f, Min: %f"%(randomMax, randomMin))

Max: 0.981654, Min: 0.015175


### 14. Create a random vector of size 30 and find the mean value

In [25]:
num = np.random.random(30)
mean = num.mean()
print(mean)

0.4674157342220526


### 15. Create a 2d array with 1 on the border and 0 inside

In [26]:
num = np.ones((10, 10))
num[1:-1, 1:-1] = 0
print(num)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 16. How to add a border (filled with 0's) around an existing array?

In [28]:
num = np.ones((5, 5))
num = np.pad(num, pad_width = 1, mode = 'constant', constant_values = 0)
print(num)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


### 17. What is the result of the following expression?

In [29]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [31]:
num = np.diag(1 + np.arange(4), k = -1)
print(num)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [32]:
num = np.zeros((8, 8),dtype = int)
num[1::2, ::2] = 1
num[::2, 1::2] = 1
print(num)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [33]:
print(np.unravel_index(99, (6, 7, 8)))

(1, 5, 3)


### 21. Create a checkerboard 8x8 matrix using the tile function

In [35]:
num = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(num)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 22. Normalize a 5x5 random matrix

In [36]:
num = np.random.random((5,5))
num = (num - np.mean (num)) / (np.std (num))
print(num)

[[-0.97097458  1.64949279  1.3220732  -0.11125412 -0.94200205]
 [-1.23335009 -1.09961597  1.51708552 -0.85113831 -0.20957906]
 [ 0.75042666  0.58748024 -0.10380454 -0.17097135 -1.19731986]
 [ 0.00809742  0.96601648  1.12517432 -0.76476545  1.4376256 ]
 [-1.3104891   1.56696177 -0.62581033 -0.98149136 -0.35786783]]


### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [37]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [38]:
num = np.dot(np.ones((5,3)), np.ones((3,2)))
print(num)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [39]:
num = np.ones((5,3)) @ np.ones((3,2))
print(num)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [40]:
num = np.arange(11)
num[(3 < num) & (num < 8)] *= -1
print(num)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


### 26. What is the output of the following script?

In [41]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


### 27. Consider an integer vector Z, which of these expressions are legal?

In [44]:
Z = np.int_([1, 0])
Z ** Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1

array([1., 0.])

### 28. What are the result of the following expressions?

In [45]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/var/folders/rd/fc3fw0297ddgrmkpvl13yhkw0000gn/T/ipykernel_3263/3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
/var/folders/rd/fc3fw0297ddgrmkpvl13yhkw0000gn/T/ipykernel_3263/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


### 29. How to round away from zero a float array ?

In [46]:
num = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(num)), num))

[  7.   7.  -4.  -6.   1.  -5. -10.   3.   1. -10.]


In [47]:
print(np.where(num > 0, np.ceil(num), np.floor(num)))

[  7.   7.  -4.  -6.   1.  -5. -10.   3.   1. -10.]


### 30. How to find common values between two arrays?

In [48]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 2 3 7 9]


### 31. How to ignore all numpy warnings (not recommended)?

In [49]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

In [50]:
_ = np.seterr(**defaults)

In [51]:
with np.errstate(all="ignore"):
    np.arange(3) / 0

### 32. Is the following expressions true

In [52]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/rd/fc3fw0297ddgrmkpvl13yhkw0000gn/T/ipykernel_3263/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

### 33. How to get the dates of yesterday, today and tomorrow?

In [55]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print(yesterday, today, tomorrow)

2022-03-21 2022-03-22 2022-03-23


### 34. How to get all the dates corresponding to the month of July 2016?

In [56]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [57]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

### 36. Extract the integer part of a random array of positive numbers using 4 different methods 

In [59]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[7. 9. 6. 9. 5. 9. 7. 0. 5. 5.]
[7. 9. 6. 9. 5. 9. 7. 0. 5. 5.]
[7. 9. 6. 9. 5. 9. 7. 0. 5. 5.]
[7 9 6 9 5 9 7 0 5 5]
[7. 9. 6. 9. 5. 9. 7. 0. 5. 5.]


### 37. Create a 5x5 matrix with row values ranging from 0 to 4 

In [61]:
Z = np.zeros((5,5))
Z = Z + np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 38. Consider a generator function that generates 10 integers and use it to build an array

In [62]:
def generate():
    for num in range(10):
        yield num

n = np.fromiter(generate(),dtype=float,count=-1)
print(n)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded 

In [63]:
num = np.linspace(0,1,11,endpoint=False)[1:]
print(num)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### 40. Create a random vector of size 10 and sort it

In [64]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.00836904 0.05879978 0.46797794 0.5468892  0.66468762 0.72703733
 0.73253394 0.77191291 0.97875473 0.98032715]


### 41. How to sum a small array faster than np.sum?

In [65]:
Z = np.arange(10)
np.add.reduce(Z)

45

### 42. Consider two random array A and B, check if they are equal

In [66]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

False
False


### 43. Make an array immutable (read-only)

In [67]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates 

In [68]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.07363677 0.58523367 0.98140548 0.28705437 0.64829512 0.18569902
 0.42459744 1.04493918 0.99712345 1.27305756]
[0.72232274 1.31154634 0.86527218 1.16721914 1.54608291 1.17834848
 1.4912968  0.80431711 1.02288664 0.82946532]


### 45. Create random vector of size 10 and replace the maximum value by 0

In [69]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.26606038 0.84237945 0.63000372 0.77819073 0.09617146 0.82255249
 0.42753953 0.87790169 0.095263   0.        ]


### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [70]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [71]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


### 48. Print the minimum and maximum representable value for each numpy scalar typ

In [72]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


### 49. How to print all the values of an array?

In [73]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 50. How to find the closest value (to a given scalar) in a vector?

In [74]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

98
