### Name: KHUN Dararith
### ID: M060813
# <center>Numpy_50

In [9]:
#1
import numpy as np

In [11]:
#2
print(np.__version__, np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/anaconda3/include']
1.20.3 None


In [12]:
#3
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
#4
arr = np.array([203, 45, 34, 64, 73, 74, 57])
print("Size of array: ", arr.size)
print("Memory size of array element: ", arr.itemsize)

Size of array:  7
Memory size of array element:  8


In [14]:
#5
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [15]:
#6
n_vector = np.zeros(10)
n_vector[4] = 1

print(n_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [18]:
#7
x = np.arange(10,50)

print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [20]:
#8
print(arr)
print("After revers: ", arr[::-1])

[203  45  34  64  73  74  57]
After revers:  [ 57  74  73  64  34  45 203]


In [22]:
#9
rshape = np.arange(9).reshape((3,3))

print(rshape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
#10
testarr = np.array([1,2,0,0,4,0])
print(testarr[np.nonzero(testarr)])

[1 2 4]


In [28]:
#11
print(np.eye(3, dtype = int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [35]:
#12
a = np.random.random((3,3,3))
print(a)

[[[0.60627525 0.4223522  0.1169931 ]
  [0.75059533 0.06631176 0.31419825]
  [0.52682158 0.76343525 0.53658398]]

 [[0.43743158 0.52827521 0.1885153 ]
  [0.54794933 0.48049568 0.2479313 ]
  [0.48614305 0.9911068  0.31954889]]

 [[0.30906826 0.02305934 0.9004352 ]
  [0.53611631 0.07277421 0.57747852]
  [0.54350748 0.12900846 0.62318914]]]


In [39]:
#13
b = np.random.random((10,10))

print("Random Matrix: ", b)
print("\nMinimum value: ", b.min())
print("Maximum value: ", b.max())

Random Matrix:  [[0.8349077  0.73584309 0.95965982 0.37533006 0.65756462 0.84642672
  0.84076647 0.73905502 0.49781808 0.66546923]
 [0.13926021 0.38826638 0.17178466 0.67162265 0.3349326  0.13013012
  0.66032814 0.16780235 0.78096203 0.01545839]
 [0.21498618 0.17339823 0.5577099  0.78009614 0.21468674 0.14827202
  0.97845455 0.99048198 0.62849019 0.80531434]
 [0.48030829 0.25917398 0.06948021 0.54994684 0.29831223 0.63741451
  0.31973615 0.5137086  0.39432886 0.53777267]
 [0.28003696 0.13436854 0.79055774 0.78657815 0.08903867 0.47084961
  0.89297602 0.64740137 0.85726456 0.10846993]
 [0.05883024 0.91516497 0.8437265  0.36409602 0.1115673  0.40364992
  0.25173711 0.27714547 0.89255618 0.45329664]
 [0.88131566 0.2178531  0.31866667 0.97676363 0.50705428 0.07501885
  0.64813561 0.90706843 0.30984927 0.96604336]
 [0.77852944 0.75674141 0.27248767 0.58915239 0.46246427 0.14994782
  0.65925174 0.79037388 0.12857138 0.55313437]
 [0.95765573 0.02665355 0.68816507 0.2217547  0.4220803  0.71318

In [42]:
#14
c = np.random.random(30)
print(c)
print("\n the mean: ", c.mean())

[0.55846036 0.85816822 0.38059966 0.29699066 0.90778321 0.93274135
 0.2367476  0.96569943 0.85862897 0.04617109 0.71911435 0.05639526
 0.25380366 0.98553369 0.42235537 0.46620555 0.99963629 0.23996305
 0.05058572 0.45630045 0.87920533 0.51689306 0.29513875 0.5474979
 0.17336828 0.01133095 0.79489275 0.90070466 0.24558281 0.35959563]

 the mean:  0.5138698015189808


In [47]:
#15
arr2d = np.ones((6,6))
arr2d[1:-1, 1:-1] = 0
print(arr2d)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [57]:
#16
d = np.ones((3,3))
d = np.pad(d, pad_width = 1, mode='constant', constant_values=0)
print(d)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [60]:
#17
# print (0 * np.nan,
# np.nan == np.nan,
# np.inf > np.nan,
# np.nan - np.nan,
# np.nan in set([np.nan]),
# 0.3 == 3*0.1)

nan False False nan True False


In [90]:
#18
e = np.diag([1,2,3,4], -1)
print(e)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [94]:
#19
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [95]:
#20
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [104]:
#21
arr = np.array([[0,1], [1,0]])
f = np.tile(arr,(4,4))
print (f)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [99]:
#22
g = np.random.random((5,5))
gmax, gmin = g.max(), g.min()
g= (g-gmin)/(gmax-gmin)
print (g)

[[0.34144257 0.24894319 0.23226637 0.40384459 0.71308063]
 [0.46050868 0.81938999 0.65899145 0.72947108 0.2990395 ]
 [0.18703611 0.73402879 0.         0.76962496 0.37062168]
 [0.54628635 0.40360575 0.6348856  0.60484827 0.20492432]
 [0.58515955 0.09669777 0.09013134 1.         0.36996566]]


In [102]:
#23
c = np.dtype([("R", np.ubyte, 1),("G", np.ubyte, 1),("B", np.ubyte, 1),("A", np.ubyte, 1)])

/var/folders/5r/z3pfvjgj2cqd27tvwzwd_plh0000gn/T/ipykernel_57599/2331718316.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  c = np.dtype([("R", np.ubyte, 1),("G", np.ubyte, 1),("B", np.ubyte, 1),("A", np.ubyte, 1)])


In [105]:
#24
g = np.random.random((5,3))
h = np.random.random((3,3))
i = np.dot(g,h)
print("The production of array: \n", i)

The production of array: 
 [[0.75008683 0.69816909 1.28733528]
 [0.62554426 0.34610009 0.79567799]
 [0.66363108 0.74347857 1.26167999]
 [0.4235022  0.18284247 0.57417957]
 [0.51699763 0.65229074 0.96698648]]


In [110]:
#25
jarr = np.arange(20)
jarr[3:8] *=  -1
print(jarr)

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10 11 12 13 14 15 16 17 18 19]


In [113]:
#26
#the result is
#9
#10

In [114]:
#27
# Z**Z not legal
# 2 << Z >> 2 not legal
# Z <- Z not legal
# 1j*Z not legal
# Z/1/1 not legal
# Z<Z>Z legal

In [115]:
#28
#The result is

#nan
#0
#[-9.22337204e+18]

In [117]:
#29
karr = np.random.uniform(-13,+12,10)
print (np.copysign(np.ceil(np.abs(karr)), karr))

[ -6.   7. -13.  -1. -11.  -9.   4.  -8.   9.   6.]


In [120]:
#30
arr1 = [2,5,3,7,5,8]
arr2 = [7,4,8,5,1,0,4]

print(np.intersect1d(arr1, arr2))

[5 7 8]


In [121]:
#31
default = np.seterr(all="ignore")
_ = np.seterr(**default)

In [123]:
#32
#False

In [124]:
#33
ytd = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",ytd)
td     = np.datetime64('today', 'D')
print("Today: ",td)
tmr  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tmr)

Yestraday:  2022-03-16
Today:  2022-03-17
Tomorrow:  2022-03-18


In [132]:
#34
print(np.arange('2016-07', '2016-08' ,dtype = 'datetime64[D]'))


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [133]:
#35
A = np.ones(5)*1
B = np.ones(5)*2
C = np.ones(5)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5, -1.5, -1.5])

In [134]:
#36
arr = np.random.uniform(0,5,5)
print(arr - arr%1)
print(np.floor(arr))
print(np.ceil(arr)-1)
print(arr.astype(int))
print(np.trunc(arr))

[4. 4. 4. 2. 3.]
[4. 4. 4. 2. 3.]
[4. 4. 4. 2. 3.]
[4 4 4 2 3]
[4. 4. 4. 2. 3.]


In [151]:
#37
larr = np.zeros((5,5))
larr += np.arange(5)
print(larr)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [154]:
#38
def generator():
    for x in range(10):
        yield x
marr = np.fromiter(generator(),dtype=float,count=-1)
print(marr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [168]:
#39
print(np.linspace(0.0, 1.0, num = 10, endpoint = False))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [180]:
#40
ran = np.random.rand(10)
print("Before sort: \n", ran)

print("After sort: \n",sort(ran))

Before sort: 
 [0.66893252 0.44216459 0.24693382 0.85445159 0.12169667 0.22669064
 0.12511968 0.61423931 0.29176324 0.45702479]
After sort: 
 [0.12169667 0.12511968 0.22669064 0.24693382 0.29176324 0.44216459
 0.45702479 0.61423931 0.66893252 0.85445159]


In [181]:
#41
n = np.array([2,4,62,5,6,7,5])
print(np.add.reduce(n))

91


In [186]:
#42
oarr1 = np.array([0,3,6,4,2,5])
oarr2 = np.array([0,3,6,4,2,5])
equal = np.allclose(oarr1,oarr2)
print(equal)
equal = np.array_equal(oarr1,oarr2)
print(equal)

True
True


In [192]:
#43
p = np.array([2,5,2,63,6,7,3,7,5,3])
p.flags.writeable = False
print(p)
print("testing of writing into array")
p[1] = 2

[ 2  5  2 63  6  7  3  7  5  3]
testing of writing into array


ValueError: assignment destination is read-only

In [193]:
#44
arr = np.random.random((10,2))
X,Y = arr[:,0], arr[:,1]
radius = np.sqrt(X**2 + Y**2)
angle = np.arctan2(Y, X)
print(radius)
print(angle)

[0.84064034 0.84228221 0.54429784 1.26454528 0.57315047 0.74726104
 0.43551154 0.7796494  0.83724918 1.31573271]
[0.51280034 0.37625173 0.88145852 0.70561156 1.24985552 0.70207469
 0.99932171 0.18699566 1.16871224 0.82134778]


In [218]:
#45
q = np.random.rand(3)
print(q)
q[q.argmax()] = 0
print(q)

[0.43661929 0.05883977 0.37015162]
[0.         0.05883977 0.37015162]


In [219]:
#46
r = np.zeros((5,5), [('x',float),('y',float)])
r['x'], r['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(r)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [220]:
#47
X = np.arange(10)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

33961.93294480225


In [221]:
#48
for dtype in [np.int8, np.int32, np.int64]:

    print(np.iinfo(dtype).min)

    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:

    print(np.finfo(dtype).min)

    print(np.finfo(dtype).max)

    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [224]:
#49
np.set_printoptions(threshold = np.inf)
s = np.zeros((12,12))
print(s)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [228]:
#50
t = np.arange(1003)
u = np.random.uniform(0,1050)
index = (np.abs(t-u)).argmin()
print(t[index])

321
