In [ ]:
#P1
import numpy as np
#P2
print(np.__version__, np.show_config())

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

In [ ]:
#P3
null_vec = np.zeros(10)
print(null_vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#P4
print(null_vec.size, null_vec.itemsize)

10 8


In [ ]:
#P5
print(np.info())

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x105750df0>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP
  

In [ ]:
#P6
null_vec = np.zeros(10)
null_vec[4] = 1
print(null_vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#P7
vec = np.arange(10, 50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#P8
vec = vec[::-1]
print(vec)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
#P9
mat = np.arange(0, 9).reshape((3,3))
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#P10
arr = [1, 2, 0, 0, 4, 0]
print(np.nonzero(arr))

(array([0, 1, 4]),)


In [ ]:
#P11
mat = np.eye(3,3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#P12
arr = np.random.random((3,3,3))
print(arr)

[[[0.79954962 0.24392352 0.64105632]
  [0.89166054 0.816642   0.57484498]
  [0.40460964 0.03448073 0.87759234]]

 [[0.8280021  0.69415228 0.85355638]
  [0.27369212 0.3497762  0.70099738]
  [0.62602874 0.64646844 0.75036228]]

 [[0.83879808 0.56094829 0.13558588]
  [0.69845571 0.0377271  0.46176871]
  [0.00740096 0.95233998 0.41298156]]]


In [ ]:
#P13
arr = np.random.random((10,10))
print(arr.min(), arr.max())

0.005393189853856395 0.9984475008332095


In [ ]:
#P14
vec = np.random.random(30)
print(vec.mean())

0.4952559043855623


In [ ]:
#P15
arr = np.ones((4, 4))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#P16
arr = np.ones((4, 4))
arr = np.pad(arr, pad_width=1)
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
#P17
#nan
#False
#False
#nan
#True
#False

In [ ]:
#P18
mat = np.diag(1 + np.arange(4), k = -1)
print(mat)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
#P19
mat = np.zeros ((8,8))
mat[1::2, ::2]= 1
mat[::2, 1::2] = 1
print(mat)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
#P20
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [ ]:
#P21
mat = np.array([[0, 1], [1, 0]])
mat = np.tile(mat, (4, 4))
print(mat)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#P22
arr = np.random.random((5, 5))
arr_max = arr.max()
arr_min = arr.min()
arr = (arr - arr_min) / (arr_max - arr_min)
print(arr)

[[0.94331101 0.15521774 0.11043254 0.51111992 0.36384458]
 [0.1536997  0.42654046 0.0996958  0.73206102 0.50815066]
 [0.61426551 0.5926297  0.50899198 0.15954974 0.95821406]
 [0.16355415 1.         0.46885806 0.12594428 0.45932218]
 [0.         0.05562445 0.87063879 0.60914749 0.92235212]]


In [ ]:
#P23
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

/var/folders/rj/grr7hzp575bckvc9tt5xpq980000gn/T/ipykernel_75336/915446527.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [ ]:
#P24
mat = np.ones((5,3)) @ np.ones((3,2))
print(mat)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
#P25
arr = np.arange(11)
arr[(3 < arr) & (arr <= 8)] *= -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [ ]:
#P26
#9
#10

In [ ]:
#P27
# The last one is legal

In [ ]:
#P28
#nan
#0
#[-9.22337204e+18]

In [ ]:
#P29
arr = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(arr)), arr))

[ 9. -6. 10. 10. -1. -9.  1. -6. -5.  4.]


In [ ]:
#P30
arr1 = np.random.randint(0,50,20)
arr2 = np.random.randint(0,50,20)
print(np.intersect1d(arr1,arr2))

[ 0  2 10 37 48]


In [ ]:
#P31
default = np.seterr(all="ignore")
_ = np.seterr(**default)

In [ ]:
#P32
#False

In [ ]:
#P33
ytd = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(f" Yesterday: {ytd}\n Today: {today}\n Tomorrow: {tomorrow}")

 Yesterday: 2022-03-09
 Today: 2022-03-10
 Tomorrow: 2022-03-11


In [ ]:
#P34
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
#P35
A = np.ones(5)*1
B = np.ones(5)*2
C = np.ones(5)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5, -1.5, -1.5])

In [ ]:
#P36
arr = np.random.uniform(0,5,5)
print(arr - arr%1)
print(np.floor(arr))
print(np.ceil(arr)-1)
print(arr.astype(int))
print(np.trunc(arr))

[0. 4. 4. 3. 2.]
[0. 4. 4. 3. 2.]
[0. 4. 4. 3. 2.]
[0 4 4 3 2]
[0. 4. 4. 3. 2.]


In [ ]:
#P37
mat = np.zeros((5,5))
mat += np.arange(5)
print(mat)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
#P38
def gen():
    for x in range(10):
        yield x
arr = np.fromiter(gen(),dtype=float,count=-1)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
#P39
vec = np.linspace(0,1,11,endpoint=False)[1:]
print(vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
#P40
vec = np.random.random(10)
vec.sort()
print(vec)
# or print(sorted(vec))

[0.08139707 0.10049888 0.17880266 0.25268691 0.39125011 0.72708853
 0.77275145 0.83294452 0.90004657 0.93388803]


In [ ]:
#P41
arr = np.arange(20)
np.add.reduce(arr)

190

In [ ]:
#P42
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

False
False


In [ ]:
#P43
arr = np.zeros(10)
arr.flags.writeable = False
arr[0] = 1

ValueError: assignment destination is read-only

In [ ]:
#P44
arr = np.random.random((10,2))
X,Y = arr[:,0], arr[:,1]
radius = np.sqrt(X**2 + Y**2)
angle = np.arctan2(Y, X)
print(radius)
print(angle)

[0.61373207 0.95233484 0.91399464 0.07354907 0.79206608 0.26816251
 1.16977489 0.48106236 1.24805073 0.4089499 ]
[1.22683349 0.46558396 1.42337957 1.09285141 0.23609614 1.15331937
 0.5651752  0.7683154  0.84731046 0.99557165]


In [ ]:
#P45
vec = np.random.random(10)
print(vec)
vec[vec.argmax()] = 0
print(vec)

[0.92097484 0.28259482 0.90300044 0.27472486 0.10980498 0.41027643
 0.63008965 0.79957657 0.32704854 0.19677188]
[0.         0.28259482 0.90300044 0.27472486 0.10980498 0.41027643
 0.63008965 0.79957657 0.32704854 0.19677188]


In [ ]:
#P46
mat = np.zeros((5,5), [('x',float),('y',float)])
mat['x'], mat['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(mat)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [ ]:
#P47
X = np.arange(10)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

33961.93294480236


In [ ]:
#P48
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [ ]:
#P49
np.set_printoptions(threshold=np.inf)
arr = np.zeros((24,24))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.

In [ ]:
#P50
arr1 = np.arange(100)
arr2 = np.random.uniform(0,100)
index = (np.abs(arr1-arr2)).argmin()
print(arr1[index])

36
