In [ ]:
#P1
import numpy as np
#P2
print(np.__version__, np.show_config())

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
1.19.2 None


In [ ]:
#P3
null_vec = np.zeros(10)
print(null_vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#P4
print(null_vec.size, null_vec.itemsize)

10 8


In [ ]:
#P5
print(np.info())

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x7ff99725ef40>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP

In [ ]:
#P6
null_vec = np.zeros(10)
null_vec[4] = 1
print(null_vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#P7
vec = np.arange(10, 50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#P8
vec = vec[::-1]
print(vec)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
#P9
mat = np.arange(0, 9).reshape((3,3))
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#P10
arr = [1, 2, 0, 0, 4, 0]
print(np.nonzero(arr))

(array([0, 1, 4]),)


In [ ]:
#P11
mat = np.eye(3,3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#P12
arr = np.random.random((3,3,3))
print(arr)

[[[0.53256676 0.0372806  0.50342644]
  [0.83022936 0.84958617 0.70935523]
  [0.60285525 0.66049964 0.98870171]]

 [[0.67700744 0.90629281 0.58902371]
  [0.00351774 0.37903457 0.70551149]
  [0.9382694  0.49713568 0.33261959]]

 [[0.88870426 0.44054051 0.71459432]
  [0.49673517 0.53130522 0.31785114]
  [0.70162406 0.84835446 0.78230312]]]


In [ ]:
#P13
arr = np.random.random((10,10))
print(arr.min(), arr.max())

0.00128917612617363 0.9953059012623274


In [ ]:
#P14
vec = np.random.random(30)
print(vec.mean())

0.5396655182900124


In [ ]:
#P15
arr = np.ones((4, 4))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#P16
arr = np.ones((4, 4))
arr = np.pad(arr, pad_width=1)
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
#P17
#nan
#False
#False
#nan
#True
#False

In [ ]:
#P18
mat = np.diag(1 + np.arange(4), k = -1)
print(mat)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
#P19
mat = np.zeros ((8,8))
mat[1::2, ::2]= 1
mat[::2, 1::2] = 1
print(mat)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
#P20
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [ ]:
#P21
mat = np.array([[0, 1], [1, 0]])
mat = np.tile(mat, (4, 4))
print(mat)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#P22
arr = np.random.random((5, 5))
arr_max = arr.max()
arr_min = arr.min()
arr = (arr - arr_min) / (arr_max - arr_min)
print(arr)

[[0.56587412 0.06463991 0.14857873 0.83356573 1.        ]
 [0.45486771 0.91789304 0.00695457 0.24971613 0.2559741 ]
 [0.23873707 0.79350242 0.28081806 0.22078452 0.06393414]
 [0.98025245 0.12803689 0.77541085 0.08386936 0.        ]
 [0.27554792 0.70819674 0.24817996 0.46331401 0.20007859]]


In [ ]:
#P23
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

/var/folders/sp/2ssjz4sd3k19q1myx36gbg_00000gn/T/ipykernel_80389/1274792624.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [ ]:
#P24
mat = np.ones((5,3)) @ np.ones((3,2))
print(mat)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
#P25
arr = np.arange(11)
arr[(3 < arr) & (arr <= 8)] *= -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [ ]:
#P26
#9
#10

In [ ]:
#P27
# The last one is legal

In [ ]:
#P28
#nan
#0
#[-9.22337204e+18]

In [ ]:
#P29
arr = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(arr)), arr))

[-5. -8. -8.  1.  3. -5. -5. -8.  9. -2.]


In [ ]:
#P30
arr1 = np.random.randint(0,50,20)
arr2 = np.random.randint(0,50,20)
print(np.intersect1d(arr1,arr2))

[ 3 17 23 36 47 48]


In [ ]:
#P31
default = np.seterr(all="ignore")
_ = np.seterr(**default)

In [ ]:
#P32
#False

In [ ]:
#P33
ytd = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(f" Yesterday: {ytd}\n Today: {today}\n Tomorrow: {tomorrow}")

 Yesterday: 2022-03-09
 Today: 2022-03-10
 Tomorrow: 2022-03-11


In [ ]:
#P34
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
#P35
A = np.ones(5)*1
B = np.ones(5)*2
C = np.ones(5)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5, -1.5, -1.5])

In [ ]:
#P36
arr = np.random.uniform(0,5,5)
print(arr - arr%1)
print(np.floor(arr))
print(np.ceil(arr)-1)
print(arr.astype(int))
print(np.trunc(arr))

[0. 4. 2. 2. 2.]
[0. 4. 2. 2. 2.]
[0. 4. 2. 2. 2.]
[0 4 2 2 2]
[0. 4. 2. 2. 2.]


In [ ]:
#P37
mat = np.zeros((5,5))
mat += np.arange(5)
print(mat)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
#P38
def gen():
    for x in range(10):
        yield x
arr = np.fromiter(gen(),dtype=float,count=-1)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
#P39
vec = np.linspace(0,1,11,endpoint=False)[1:]
print(vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
#P40
vec = np.random.random(10)
vec.sort()
print(vec)
# or print(sorted(vec))

[0.08212184 0.22951541 0.25088435 0.45508887 0.46368428 0.82175894
 0.8276966  0.88352554 0.91600515 0.9845995 ]


In [ ]:
#P41
arr = np.arange(20)
np.add.reduce(arr)

190

In [ ]:
#P42
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

False
False


In [ ]:
#P43
arr = np.zeros(10)
arr.flags.writeable = False
arr[0] = 1

ValueError: assignment destination is read-only

In [ ]:
#P44
arr = np.random.random((10,2))
X,Y = arr[:,0], arr[:,1]
radius = np.sqrt(X**2 + Y**2)
angle = np.arctan2(Y, X)
print(radius)
print(angle)

[0.44947492 1.25912202 0.9930766  0.70431871 1.22016972 0.88131412
 0.55295391 0.94269832 0.96431634 0.57867139]
[1.257056   0.72776149 0.56835785 0.15739331 0.75668655 0.36683092
 1.185978   0.86565863 0.00241714 0.83780809]


In [ ]:
#P45
vec = np.random.random(10)
print(vec)
vec[vec.argmax()] = 0
print(vec)

[0.64453703 0.5141235  0.10455463 0.99293195 0.7457206  0.07384736
 0.77268734 0.14349279 0.17899791 0.14287998]
[0.64453703 0.5141235  0.10455463 0.         0.7457206  0.07384736
 0.77268734 0.14349279 0.17899791 0.14287998]


In [ ]:
#P46
mat = np.zeros((5,5), [('x',float),('y',float)])
mat['x'], mat['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(mat)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [ ]:
#P47
X = np.arange(10)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

33961.93294480236


In [ ]:
#P48
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [ ]:
#P49
np.set_printoptions(threshold=np.inf)
arr = np.zeros((24,24))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.

In [ ]:
#P50
arr1 = np.arange(100)
arr2 = np.random.uniform(0,100)
index = (np.abs(arr1-arr2)).argmin()
print(arr1[index])

47
