In [1]:
#P1
import numpy as np
#P2
print(np.__version__, np.show_config())

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

In [2]:
#P3
null_vec = np.zeros(10)
print(null_vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
#P4
print(null_vec.size, null_vec.itemsize)

10 8


In [4]:
#P5
print(np.info())

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x7efd85f5e990>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP

In [5]:
#P6
null_vec = np.zeros(10)
null_vec[4] = 1
print(null_vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:
#P7
vec = np.arange(10, 50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
#P8
vec = vec[::-1]
print(vec)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [8]:
#P9
mat = np.arange(0, 9).reshape((3,3))
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
#P10
arr = [1, 2, 0, 0, 4, 0]
print(np.nonzero(arr))

(array([0, 1, 4]),)


In [10]:
#P11
mat = np.eye(3,3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
#P12
arr = np.random.random((3,3,3))
print(arr)

[[[0.70737136 0.21575195 0.54150312]
  [0.17915335 0.2368306  0.11291649]
  [0.65429022 0.17044258 0.26813761]]

 [[0.99746804 0.84123478 0.69448017]
  [0.12299132 0.69556201 0.52916216]
  [0.26860526 0.54286136 0.11760765]]

 [[0.81526509 0.09918277 0.9575842 ]
  [0.30633761 0.36917596 0.61351523]
  [0.4631549  0.05208838 0.41873929]]]


In [12]:
#P13
arr = np.random.random((10,10))
print(arr.min(), arr.max())

0.027610173002544758 0.9775835143983388


In [13]:
#P14
vec = np.random.random(30)
print(vec.mean())

0.49731420039139596


In [14]:
#P15
arr = np.ones((4, 4))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [15]:
#P16
arr = np.ones((4, 4))
arr = np.pad(arr, pad_width=1)
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [16]:
#P18
mat = np.diag(1 + np.arange(4), k = -1)
print(mat)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [17]:
#P19
mat = np.zeros ((8,8))
mat[1::2, ::2]= 1
mat[::2, 1::2] = 1
print(mat)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [18]:
#P20
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [19]:
#P21
mat = np.array([[0, 1], [1, 0]])
mat = np.tile(mat, (4, 4))
print(mat)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [20]:
#P22
arr = np.random.random((5, 5))
arr_max = arr.max()
arr_min = arr.min()
arr = (arr - arr_min) / (arr_max - arr_min)
print(arr)

[[0.07923432 0.         0.42830057 0.76489334 0.45183771]
 [0.16958551 0.39139513 0.06821393 0.58496451 0.87365024]
 [0.78601004 0.21924575 0.60358816 0.21127804 0.18005188]
 [0.69002731 0.90711438 0.44110388 0.28449207 0.11366485]
 [0.36687643 0.37461251 0.37222277 1.         0.84690705]]


In [21]:
#P23
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


In [22]:
#P24
mat = np.ones((5,3)) @ np.ones((3,2))
print(mat)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [23]:
#P25
arr = np.arange(11)
arr[(3 < arr) & (arr <= 8)] *= -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [24]:
#P29
arr = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(arr)), arr))

[  5.   8.  10.  -6.  -1. -10.   7.  -8.   4.   6.]


In [25]:
#P30
arr1 = np.random.randint(0,50,20)
arr2 = np.random.randint(0,50,20)
print(np.intersect1d(arr1,arr2))

[ 7 12 31 35 38 44]


In [26]:
#P31
default = np.seterr(all="ignore")
_ = np.seterr(**default)

In [27]:
#P33
ytd = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(f" Yesterday: {ytd}\n Today: {today}\n Tomorrow: {tomorrow}")

 Yesterday: 2022-03-21
 Today: 2022-03-22
 Tomorrow: 2022-03-23


In [28]:
#P34
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [29]:
#P35
A = np.ones(5)*1
B = np.ones(5)*2
C = np.ones(5)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5, -1.5, -1.5])

In [30]:
#P36
arr = np.random.uniform(0,5,5)
print(arr - arr%1)
print(np.floor(arr))
print(np.ceil(arr)-1)
print(arr.astype(int))
print(np.trunc(arr))

[3. 0. 3. 4. 4.]
[3. 0. 3. 4. 4.]
[3. 0. 3. 4. 4.]
[3 0 3 4 4]
[3. 0. 3. 4. 4.]


In [31]:
#P37
mat = np.zeros((5,5))
mat += np.arange(5)
print(mat)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [32]:
#P38
def gen():
    for x in range(10):
        yield x
arr = np.fromiter(gen(),dtype=float,count=-1)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [33]:
#P39
vec = np.linspace(0,1,11,endpoint=False)[1:]
print(vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [34]:
#P40
vec = np.random.random(10)
vec.sort()
print(vec)

[0.03967638 0.10831465 0.26692135 0.37035281 0.54168878 0.647397
 0.77694329 0.78758469 0.84375766 0.92395891]


In [35]:
#P41
arr = np.arange(20)
np.add.reduce(arr)

190

In [36]:
#P42
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

False
False


In [38]:
#P44
arr = np.random.random((10,2))
X,Y = arr[:,0], arr[:,1]
radius = np.sqrt(X**2 + Y**2)
angle = np.arctan2(Y, X)
print(radius)
print(angle)

[0.60885448 0.68944916 0.89269483 0.40062219 0.36360778 1.02644639
 0.87572959 0.65418286 0.74208387 0.67979753]
[1.27859727 1.00320547 0.83293262 1.17430048 1.1562896  0.27428225
 0.50427275 0.76587174 0.133293   0.82662916]


In [39]:
#P45
vec = np.random.random(10)
print(vec)
vec[vec.argmax()] = 0
print(vec)

[0.26041263 0.62393198 0.84765452 0.87012549 0.8947013  0.47464558
 0.40869333 0.62570578 0.49148911 0.54945146]
[0.26041263 0.62393198 0.84765452 0.87012549 0.         0.47464558
 0.40869333 0.62570578 0.49148911 0.54945146]


In [40]:
#P46
mat = np.zeros((5,5), [('x',float),('y',float)])
mat['x'], mat['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(mat)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [41]:
#P47
X = np.arange(10)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

33961.93294480236


In [42]:
#P48
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [43]:
#P49
np.set_printoptions(threshold=np.inf)
arr = np.zeros((24,24))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.

In [44]:
#P50
arr1 = np.arange(100)
arr2 = np.random.uniform(0,100)
index = (np.abs(arr1-arr2)).argmin()
print(arr1[index])

70
